from enum import Enum


class Event(str, Enum):
    CONNECTED = "connected"
    DISCONNECTED = "disconnect"
    ERROR = "error"
    CONNECTION_ERROR = "connect_error"
    REVOKED_CONNECTION = "kicked_room"
    RAID_ATTACK = "attack"
    RAID_START = "start"
    RAID_END = "end"
    RAID_RETIRE = "retire"
    RAID_CYCLE_RESET = "cycle_reset"
    RAID_TARGET_CHANGED = "target"


class TitanPart(str, Enum):
    ArmorLegUpperRight = "ArmorLegUpperRight"
    ArmorHandLeft = "ArmorHandLeft"
    ArmorHandRight = "ArmorHandRight"
    ArmorLegUpperLeft = "ArmorLegUpperLeft"
    ArmorChestUpper = "ArmorChestUpper"
    ArmorArmUpperRight = "ArmorArmUpperRight"
    ArmorArmUpperLeft = "ArmorArmUpperLeft"
    ArmorHead = "ArmorHead"
    BodyLegUpperRight = "BodyLegUpperRight"
    BodyHandLeft = "BodyHandLeft"
    BodyHandRight = "BodyHandRight"
    BodyLegUpperLeft = "BodyLegUpperLeft"
    BodyChestUpper = "BodyChestUpper"
    BodyArmUpperRight = "BodyArmUpperRight"
    BodyArmUpperLeft = "BodyArmUpperLeft"
    BodyHead = "BodyHead"
    SkeletonLegUpperRight = "SkeletonLegUpperRight"
    SkeletonHandLeft = "SkeletonHandLeft"
    SkeletonHandRight = "SkeletonHandRight"
    SkeletonLegUpperLeft = "SkeletonLegUpperLeft"
    SkeletonChestUpper = "SkeletonChestUpper"
    SkeletonArmUpperRight = "SkeletonArmUpperRight"
    SkeletonArmUpperLeft = "SkeletonArmUpperLeft"
    SkeletonHead = "SkeletonHead"


class CardBonus(str, Enum):
    TeamTacticsClanMoraleBoost = "TeamTacticsClanMoraleBoost"
    MirrorForceBoost = "MirrorForceBoost"


class Card(str, Enum):
    MoonBeam = "MoonBeam"
    Fragmentize = "Fragmentize"
    SkullBash = "SkullBash"
    RazorWind = "RazorWind"
    WhipOfLightning = "WhipOfLightning"
    BurstCount = "BurstCount"
    Purify = "Purify"
    LimbBurst = "LimbBurst"
    FlakShot = "FlakShot"
    Haymaker = "Haymaker"
    ChainLightning = "ChainLightning"
    MirrorForce = "MirrorForce"
    CelestialStatic = "CelestialStatic"
    BurningAttack = "BurningAttack"
    PoisonAttack = "PoisonAttack"
    DecayingAttack = "DecayingAttack"
    Fuse = "Fuse"
    Shadow = "Shadow"
    PlagueAttack = "PlagueAttack"
    Disease = "Disease"
    Swarm = "Swarm"
    RuinousRust = "RuinousRust"
    RuneAttack = "RuneAttack"
    ExecutionersAxe = "ExecutionersAxe"
    CrushingVoid = "CrushingVoid"
    MentalFocus = "MentalFocus"
    ImpactAttack = "ImpactAttack"
    InnerTruth = "InnerTruth"
    FinisherAttack = "FinisherAttack"
    SuperheatMetal = "SuperheatMetal"
    BurstBoost = "BurstBoost"
    LimbSupport = "LimbSupport"
    TotemFairySkill = "TotemFairySkill"
    TeamTactics = "TeamTactics"
    SpinalTap = "SpinalTap"


class Enemy(str, Enum):
    Enemy1 = "Enemy1"
    Enemy2 = "Enemy2"
    Enemy3 = "Enemy3"
    Enemy4 = "Enemy4"
    Enemy5 = "Enemy5"
    Enemy6 = "Enemy6"
    Enemy7 = "Enemy7"
    Enemy8 = "Enemy8"


class EnemyName(str, Enum):
    Lojak = "Lojak"
    Takedar = "Takedar"
    Jukk = "Jukk"
    Sterl = "Sterl"
    Mohaca = "Mohaca"
    Terro = "Terro"
    Klonk = "Klonk"
    Priker = "Priker"
