from enum import Enum


class Event(str, Enum):
    CONNECTED = "connected"
    DISCONNECTED = "disconnect"
    ERROR = "error"
    CONNECTION_ERROR = "connect_error"
    CLAN_REMOVED = "unsub_clan"
    RAID_ATTACK = "attack"
    RAID_START = "start"
    CLAN_ADDED_RAID_START = "sub_start"
    RAID_END = "end"
    RAID_RETIRE = "retire"
    RAID_CYCLE_RESET = "cycle_reset"
    CLAN_ADDED_CYCLE = "sub_cycle"
    RAID_TARGET_CHANGED = "target"


class TitanPart(str, Enum):
    ArmorLegRight = "ArmorLegUpperRight"
    ArmorHandLeft = "ArmorHandLeft"
    ArmorHandRight = "ArmorHandRight"
    ArmorLegLeft = "ArmorLegUpperLeft"
    ArmorChest = "ArmorChestUpper"
    ArmorArmRight = "ArmorArmUpperRight"
    ArmorArmLeft = "ArmorArmUpperLeft"
    ArmorHead = "ArmorHead"
    BodyLegRight = "BodyLegUpperRight"
    BodyHandLeft = "BodyHandLeft"
    BodyHandRight = "BodyHandRight"
    BodyLegLeft = "BodyLegUpperLeft"
    BodyChest = "BodyChestUpper"
    BodyArmRight = "BodyArmUpperRight"
    BodyArmLeft = "BodyArmUpperLeft"
    BodyHead = "BodyHead"
    SkeletonLegRight = "SkeletonLegUpperRight"
    SkeletonHandLeft = "SkeletonHandLeft"
    SkeletonHandRight = "SkeletonHandRight"
    SkeletonLegLeft = "SkeletonLegUpperLeft"
    SkeletonChest = "SkeletonChestUpper"
    SkeletonArmRight = "SkeletonArmUpperRight"
    SkeletonArmLeft = "SkeletonArmUpperLeft"
    SkeletonHead = "SkeletonHead"


class CardBonus(str, Enum):
    TeamTacticsClanMoraleBoost = "TeamTacticsClanMoraleBoost"
    MirrorForceBoost = "MirrorForceBoost"


class Card(str, Enum):
    MoonBeam = "MoonBeam"
    Fragmentize = "Fragmentize"
    SkullBash = "SkullBash"
    RazorWind = "RazorWind"
    WhipOfLightning = "WhipOfLightning"
    ClanshipBarrage = "BurstCount"
    PurifyingBlast = "Purify"
    PsychicShackles = "LimbBurst"
    FlakShot = "FlakShot"
    CosmicHaymaker = "Haymaker"
    ChainOfVengeance = "ChainLightning"
    MirrorForce = "MirrorForce"
    CelestialStatic = "CelestialStatic"
    BlazingInferno = "BurningAttack"
    AcidDrench = "PoisonAttack"
    DecayingStrike = "DecayingAttack"
    FusionBomb = "Fuse"
    GrimShadow = "Shadow"
    ThrivingPlague = "PlagueAttack"
    Radioactivity = "Disease"
    RavenousSwarm = "Swarm"
    RuinousRain = "RuinousRust"
    CorrosiveBubbles = "PowerBubble"
    Maelstrom = "RuneAttack"
    CrushingInstinct = "ExecutionersAxe"
    InsanityVoid = "CrushingVoid"
    RancidGas = "MentalFocus"
    InspiringForce = "ImpactAttack"
    SoulFire = "InnerTruth"
    VictoryMarch = "FinisherAttack"
    PrismaticRift = "SuperheatMetal"
    AncestralFavor = "BurstBoost"
    GraspingVines = "LimbSupport"
    TotemOfPower = "TotemFairySkill"
    TeamTactics = "TeamTactics"
    SkeletalSmash = "SpinalTap"
    AstralEcho = "AstralEcho"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class Enemy(str, Enum):
    Enemy1 = "Enemy1"
    Enemy2 = "Enemy2"
    Enemy3 = "Enemy3"
    Enemy4 = "Enemy4"
    Enemy5 = "Enemy5"
    Enemy6 = "Enemy6"
    Enemy7 = "Enemy7"
    Enemy8 = "Enemy8"


class EnemyName(str, Enum):
    Lojak = "Lojak"
    Takedar = "Takedar"
    Jukk = "Jukk"
    Sterl = "Sterl"
    Mohaca = "Mohaca"
    Terro = "Terro"
    Klonk = "Klonk"
    Priker = "Priker"


class TargetState(str, Enum):
    NoTarget = "0"
    Crossed = "1"
    Checked = "2"


class TargetStatePart(str, Enum):
    Head = "Head"
    Chest = "ChestUpper"
    ArmRight = "ArmUpperRight"
    ArmLeft = "ArmUpperLeft"
    LegRight = "LegUpperRight"
    LegLeft = "LegUpperLeft"
    HandRight = "HandRight"
    HandLeft = "HandLeft"


class TitanRaidBonus(str, Enum):
    RaidAttackDuration = "RaidAttackDuration"
    AfflictedDamage = "AfflictedDamage"
    AfflictedDuration = "AfflictedDuration"
    LimbDamage = "LimbDamage"
    AllRaidDamage = "AllRaidDamage"
    SupportEffect = "SupportEffect"
    AfflictedChance = "AfflictedChance"
    ChestDamage = "ChestDamage"
    HeadDamage = "HeadDamage"
    BodyDamage = "BodyDamage"
    ArmorDamage = "ArmorDamage"
    BurstDamage = "BurstDamage"
    BurstChance = "BurstChance"


class Artifact(str, Enum):
    BookOfShadows = "Book of Shadows"
    ChargedCard = "Charged Card"
    StoneOfTheValrunes = "Stone of the Valrunes"
    ChestOfContentment = "Chest of Contentment"
    HeroicShield = "Heroic Shield"
    BookOfProphecy = "Book of Prophecy"
    KhrysosBowl = "Khrysos Bowl"
    ZakynthosCoin = "Zakynthos Coin"
    GreatFayMedallion = "Great Fay Medallion"
    NekoSculpture = "Neko Sculpture"
    CoinsOfEbizu = "Coins of Ebizu"
    TheBronzedCompass = "The Bronzed Compass"
    EvergrowingStack = "Evergrowing Stack"
    FluteOfTheSoloist = "Flute of the Soloist"
    HeavenlySword = "Heavenly Sword"
    DivineRetribution = "Divine Retribution"
    DrunkenHammer = "Drunken Hammer"
    SamosekSword = "Samosek Sword"
    TheRetaliator = "The Retaliator"
    StryfesPeace = "Stryfe's Peace"
    HerosBlade = "Hero's Blade"
    TheSwordOfStorms = "The Sword of Storms"
    FuriesBow = "Furies Bow"
    CharmOfTheAncient = "Charm of the Ancient"
    TinyTitanTree = "Tiny Titan Tree"
    HelmOfHermes = "Helm of Hermes"
    FruitOfEden = "Fruit of Eden"
    InfluentialElixir = "Influential Elixir"
    ShimmeringOil = "Shimmering Oil"
    GoldenScope = "Golden Scope"
    ORyansCharm = "O'Ryan's Charm"
    HeartOfStorms = "Heart of Storms"
    ApolloOrb = "Apollo Orb"
    StickyFruit = "Sticky Fruit"
    HadesOrb = "Hades Orb"
    EarringsOfPortara = "Earrings of Portara"
    AvianFeather = "Avian Feather"
    RestoredRuneHeart = "Restored Rune Heart"
    DurendalSword = "Durendal Sword"
    HelheimSkull = "Helheim Skull"
    OathsBurden = "Oath's Burden"
    CrownOfTheConstellation = "Crown of the Constellation"
    TitaniasSceptre = "Titania's Sceptre"
    FaginsGrip = "Fagin's Grip"
    RingOfCalisto = "Ring of Calisto"
    BladeOfDamocles = "Blade of Damocles"
    HelmetOfMadness = "Helmet of Madness"
    TitaniumPlating = "Titanium Plating"
    MoonlightBracelet = "Moonlight Bracelet"
    AmethystStaff = "Amethyst Staff"
    SwordOfTheRoyals = "Sword of the Royals"
    SpearitsVigil = "Spearit's Vigil"
    TheCobaltPlate = "The Cobalt Plate"
    SigilsOfJudgement = "Sigils of Judgement"
    FoliageOfTheKeeper = "Foliage of the Keeper"
    InvadersGjallarhorn = "Invader's Gjallarhorn"
    TitansMask = "Titan's Mask"
    RoyalToxin = "Royal Toxin"
    LaborersPendant = "Laborer's Pendant"
    BringerOfRagnarok = "Bringer of Ragnarok"
    ParchmentOfForesight = "Parchment of Foresight"
    ElixirOfEden = "Elixir of Eden"
    TwinBracers = "Twin Bracers"
    CosmicSextant = "Cosmic Sextant"
    EndlessBandolier = "Endless Bandolier"
    PearlOfOblivion = "Pearl of Oblivion"
    HourglassOfTheImpatient = "Hourglass of the Impatient"
    PhantomTimepiece = "Phantom Timepiece"
    ForbiddenScroll = "Forbidden Scroll"
    RingOfFealty = "Ring of Fealty"
    GlacialAxe = "Glacial Axe"
    Aegis = "Aegis"
    SwampGauntlet = "Swamp Gauntlet"
    InfinityPendulum = "Infinity Pendulum"
    GloveOfKuma = "Glove of Kuma"
    TitanSpear = "Titan Spear"
    OakStaff = "Oak Staff"
    TheArcanaCloak = "The Arcana Cloak"
    HuntersOintment = "Hunter's Ointment"
    AmbrosiaElixir = "Ambrosia Elixir"
    MysticStaff = "Mystic Staff"
    MysticalBeansOfSenzu = "Mystical Beans of Senzu"
    EggOfFortune = "Egg of Fortune"
    DivineChalice = "Divine Chalice"
    InvadersShield = "Invader's Shield"
    AxeOfMuerte = "Axe of Muerte"
    EssenceOfTheKitsune = "Essence of the Kitsune"
    BootsOfHermes = "Boots of Hermes"
    UnboundGauntlet = "Unbound Gauntlet"
    OberonPendant = "Oberon Pendant"
    LuckyFootOfAlmiraj = "Lucky Foot of Al-mi'raj"
    LostKingsMask = "Lost King's Mask"
    StaffOfRadiance = "Staff of Radiance"
    MorgelaiSword = "Morgelai Sword"
    RingingStone = "Ringing Stone"
    QuillOfScrolls = "Quill of Scrolls"
    OldKingsStamp = "Old King's Stamp"
    TheMastersSword = "The Master's Sword"
    TheMagnifier = "The Magnifier"
    TheTreasureOfFergus = "The Treasure of Fergus"
    TheWhiteDwarf = "The White Dwarf"
    AramSpear = "Aram Spear"
    WardOfTheDarkness = "Ward of the Darkness"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class ExportCard(str, Enum):
    MoonBeam = "Moon Beam"
    Fragmentize = "Fragmentize"
    SkullBash = "Skull Bash"
    RazorWind = "Razor Wind"
    WhipOfLightning = "Whip of Lightning"
    ClanshipBarrage = "Clanship Barrage"
    PurifyingBlast = "Purifying Blast"
    PsychicShackles = "Psychic Shackles"
    FlakShot = "Flak Shot"
    CosmicHaymaker = "Cosmic Haymaker"
    ChainOfVengeance = "Chain of Vengeance"
    MirrorForce = "Mirror Force"
    CelestialStatic = "Celestial Static"
    BlazingInferno = "Blazing Inferno"
    AcidDrench = "Acid Drench"
    DecayingStrike = "Decaying Strike"
    FusionBomb = "Fusion Bomb"
    GrimShadow = "Grim Shadow"
    ThrivingPlague = "Thriving Plague"
    Radioactivity = "Radioactivity"
    RavenousSwarm = "Ravenous Swarm"
    RuinousRain = "Ruinous Rain"
    CorrosiveBubbles = "Corrosive Bubbles"
    Maelstrom = "Maelstrom"
    CrushingInstinct = "Crushing Instinct"
    InsanityVoid = "Insanity Void"
    RancidGas = "Rancid Gas"
    InspiringForce = "Inspiring Force"
    SoulFire = "Soul Fire"
    VictoryMarch = "Victory March"
    PrismaticRift = "Prismatic Rift"
    AncestralFavor = "Ancestral Favor"
    GraspingVines = "Grasping Vines"
    TotemOfPower = "Totem of Power"
    TeamTactics = "Team Tactics"
    SkeletalSmash = "Skeletal Smash"
    AstralEcho = "Astral Echo"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class Equipment(str, Enum):
    WoodlandWarrior = "Woodland Warrior"
    RuthlessNecromancer = "Ruthless Necromancer"
    AngelicGuardian = "Angelic Guardian"
    TreasureHunter = "Treasure Hunter"
    DarkPredator = "Dark Predator"
    ChaoticAlchemist = "Chaotic Alchemist"
    FatalSamurai = "Fatal Samurai"
    AncientWarrior = "Ancient Warrior"
    PhantomPresence = "Phantom Presence"
    CyberneticEnhancements = "Cybernetic Enhancements"
    DragonSlayer = "Dragon Slayer"
    DefenderOfTheEgg = "Defender of the Egg"
    TheHeartbreaker = "The Heartbreaker"
    SnowMaster = "Snow Master"
    MidnightRaven = "Midnight Raven"
    TheRockstar = "The Rockstar"
    SurfStrike = "Surf Strike"
    VikingKing = "Viking King"
    TheSlyWolf = "The Sly Wolf"
    ChainedClockwork = "Chained Clockwork"
    SolarParagon = "Solar Paragon"
    FrostWarden = "Frost Warden"
    ToxicSlayer = "Toxic Slayer"
    DefiantSpellslinger = "Defiant Spellslinger"
    TitanAttacker = "Titan Attacker"
    ScarecrowJack = "Scarecrow Jack"
    SledSeason = "Sled Season"
    ShadowDisciple = "Shadow Disciple"
    AnniversaryPlatinum = "Anniversary Platinum"
    MechanizedSword = "Mechanized Sword"
    ChillsandThrills = "Chills and Thrills"
    LunarFestival = "Lunar Festival"
    EternalMonk = "Eternal Monk"
    ThunderingDeity = "Thundering Deity"
    BlessedBishop = "Blessed Bishop"
    NobleFencer = "Noble Fencer"
    TheFallenAngel = "The Fallen Angel"
    DedicatedFan = "Dedicated Fan"
    BoneMender = "Bone Mender"
    CelestialEnchanter = "Celestial Enchanter"
    ComboBreaker = "Combo Breaker"
    GrimReaper = "Grim Reaper"
    JackFrost = "Jack Frost"
    NimbleHunter = "Nimble Hunter"
    SweetsandTreats = "Sweets and Treats"
    HiddenViper = "Hidden Viper"
    HeirOfShadows = "Heir of Shadows"
    HeirOfLight = "Heir of Light"
    KorTheWhisperingWave = "Kor, the Whispering Wave"
    StyxsisTheSingleTouch = "Styxsis, the Single Touch"
    DigitalIdol = "Digital Idol"
    AzureKnight = "Azure Knight"
    GrillMaster = "Grill Master"
    AncientVampire = "Ancient Vampire"
    BlackKnight = "Black Knight"
    AnniversaryJade = "Anniversary Jade"
    TinyTitan = "Tiny Titan"
    ImmaculateArbiter = "Immaculate Arbiter"
    LoveStruck = "Love Struck"
    BraveMinstrel = "Brave Minstrel"
    ForsakenBattlemage = "Forsaken Battlemage"
    InspiringCaptain = "Inspiring Captain"
    CutthroatRazorfist = "Cutthroat Razorfist"
    RockQueen = "Rock Queen"
    TwilightTemplar = "Twilight Templar"
    SkyboundShepherd = "Skybound Shepherd"
    AquaticDefender = "Aquatic Defender"
    ShaeTheRadiantBeacon = "Shae, the Radiant Beacon"
    FairyKing = "Fairy King"
    CacklingWitch = "Cackling Witch"
    SpellMaster = "Spell Master"
    FestiveBandit = "Festive Bandit"
    InspiredLieutenant = "Inspired Lieutenant"
    GigaGolem = "Giga-Golem"
    CherubicEmissary = "Cherubic Emissary"
    SpaceKnight = "Space Knight"
    HellCook = "Hell Cook"
    CatNinja = "Cat Ninja"
    ForestSylph = "Forest Sylph"
    TitanCrusher = "Titan Crusher"
    RollPlayer = "Roll Player"
    DungeonExplorer = "Dungeon Explorer"
    CosmicWanderer = "Cosmic Wanderer"
    WeekendWarrior = "Weekend Warrior"
    BelialTheFossilizedSymbiote = "Belial, the Fossilized Symbiote"
    SummerSweetheart = "Summer Sweetheart"
    SkywingSkirmisher = "Skywing Skirmisher"
    HeadlessHorsemaster = "Headless Horsemaster"
    BoneKnight = "Bone Knight"
    PrestigiousChampion = "Prestigious Champion"
    MadScientist = "Mad Scientist"
    GingerbreadMaster = "Gingerbread Master"
    LuckyFoxSaint = "Lucky Fox Saint"
    TavernDancer = "Tavern Dancer"
    ScubaDive = "Scuba Diver"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class Pet(str, Enum):
    Nova = "Nova"
    Toto = "Toto"
    Cerberus = "Cerberus"
    Mousy = "Mousy"
    Harker = "Harker"
    Bubbles = "Bubbles"
    Demos = "Demos"
    Tempest = "Tempest"
    Basky = "Basky"
    Scraps = "Scraps"
    Zero = "Zero"
    Polly = "Polly"
    Hamy = "Hamy"
    Phobos = "Phobos"
    Fluffers = "Fluffers"
    Kit = "Kit"
    Soot = "Soot"
    Klack = "Klack"
    Cooper = "Cooper"
    Jaws = "Jaws"
    Xander = "Xander"
    Griff = "Griff"
    Basil = "Basil"
    Bash = "Bash"
    Violet = "Violet"
    Annabelle = "Annabelle"
    Effie = "Effie"
    Percy = "Percy"
    Cosmos = "Cosmos"
    Taffy = "Taffy"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class Monument(str, Enum):
    SkullIsland = "Skull Island"
    BuriedBooty = "Buried Booty"
    KeelhaulReef = "Keelhaul Reef"
    BeastHuntersGrave = "Beast Hunter's Grave"
    DroidFactory = "Droid Factory"
    RosabellasVillage = "Rosabella's Village"
    FreebooterOutpost = "Freebooter Outpost"
    RedWaterWreckage = "Red Water Wreckage"
    OldSaltTradingPost = "Old Salt Trading Post"
    ChestersonIsland = "Chesterson Island"
    SkyrentValley = "Skyrent Valley"
    BridgeOfEternalBalance = "Bridge of Eternal Balance"
    BlessedPlains = "Blessed Plains"
    VoidTemple = "Void Temple"
    CelestialsThumb = "Celestial's Thumb"
    SwordMastersShrine = "Sword Master's Shrine"
    PalaceOfOneThousandWaterfalls = "Palace of One Thousand Waterfalls"
    EvergoldCity = "Evergold City"
    TempleOfTheEternalFlame = "Temple of the Eternal Flame"
    FreemanasHotSprings = "Freemana's Hot Springs"
    KingCobraStatue = "King Cobra Statue"
    TwinViperRivers = "Twin Viper Rivers"
    NightcragMarket = "Nightcrag Market"
    ValleyOfBlades = "Valley of Blades"
    MoundOfBrothersMeet = "Mound of Brothers' Meet"
    PortalOfShadows = "Portal of Shadows"
    AncientOriginOfTheVipers = "Ancient Origin of the Vipers"
    ThievesGuild = "Thieves' Guild"
    HideoutOfStratagem = "Hideout of Stratagem"
    MidnightPass = "Midnight Pass"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)


class Skill(str, Enum):
    KnightsValor = "Knight's Valor"
    ChivalricOrder = "Chivalric Order"
    AngelicRadiance = "Angelic Radiance"
    WillOfMidas = "Will of Midas"
    CleavingStrike = "Cleaving Strike"
    Rejuvenation = "Rejuvenation"
    FairyCharm = "Fairy Charm"
    BarbaricFury = "Barbaric Fury"
    DivineWrath = "Divine Wrath"
    TwilightGathering = "Twilight Gathering"
    EventideAfterglow = "Eventide Afterglow"
    PetEvolution = "Pet Evolution"
    SummonInferno = "Summon Inferno"
    HeartOfGold = "Heart of Gold"
    CompanionWarfare = "Companion Warfare"
    EmberArts = "Ember Arts"
    LightningBurst = "Lightning Burst"
    CombatTechniques = "Combat Techniques"
    VolcanicEruption = "Volcanic Eruption"
    FlashZip = "Flash Zip"
    SummoningCircle = "Summoning Circle"
    BurningPassion = "Burning Passion"
    MasterCommander = "Master Commander"
    TacticalInsight = "Tactical Insight"
    HeroicMight = "Heroic Might"
    AerialAssault = "Aerial Assault"
    CoordinatedOffensive = "Coordinated Offensive"
    SearingLight = "Searing Light"
    AnchoringShot = "Anchoring Shot"
    AstralAwakening = "Astral Awakening"
    CommandSupremacy = "Command Supremacy"
    VoltaicSails = "Voltaic Sails"
    GalvanizedMast = "Galvanized Mast"
    PhantomVengeance = "Phantom Vengeance"
    LimitBreak = "Limit Break"
    EternalDarkness = "Eternal Darkness"
    ManaSiphon = "Mana Siphon"
    ManniMana = "Manni Mana"
    DimensionalShift = "Dimensional Shift"
    LightningStrike = "Lightning Strike"
    ForbiddenContract = "Forbidden Contract"
    PhantomControl = "Phantom Control"
    NightmarePuppeteer = "Nightmare Puppeteer"
    TerrifyingPact = "Terrifying Pact"
    MasterThief = "Master Thief"
    Assassinate = "Assassinate"
    SummonDagger = "Summon Dagger"
    Cloaking = "Cloaking"
    Backstab = "Backstab"
    PoisonEdge = "Poison Edge"
    Ambush = "Ambush"
    DeadlyFocus = "Deadly Focus"
    WeakpointThrow = "Weakpoint Throw"
    LoadedDice = "Loaded Dice"
    MarkOfDeath = "Mark of Death"
    Transmutation = "Transmutation"
    GoldGun = "Gold Gun"
    ChestersonIncense = "Chesterson Incense"
    MidasUltimate = "Midas Ultimate"
    MagnumOpus = "Magnum Opus"
    LovePotion = "Love Potion"
    MidasOverflow = "Midas Overflow"
    AuricShot = "Auric Shot"
    SproutingSalts = "Sprouting Salts"
    RoyalContract = "Royal Contract"
    ExplosivesExpert = "Explosives Expert"

    # Placeholder for api changes
    UNKNOWN = "UNKNOWN"

    @classmethod
    def _missing_(cls, value: object):
        return cls(cls.UNKNOWN)
